# The overall format is standard TOML format, v0.5.0.
# The name of the mod loader type to load - for regular FML @Mod mods it should be javafml
modLoader="javafml" #mandatory

# A version range to match for said mod loader - for regular FML @Mod it will be the forge version
loaderVersion="[40,)" #mandatory
issueTrackerURL="https://github.com/Sinhika/simplecobalt/issues"
license="LGPL 3"
logoFile="logo.png"

[[mods]]
modId="simplecobalt"
version="${file.jarVersion}"
displayName="akkamaddi's Simple Cobalt"
updateJSONURL="https://raw.githubusercontent.com/Sinhika/simplecobalt/1.18/update.json"
displayURL="https://www.curseforge.com/minecraft/mc-mods/simple-cobalt"
credits="Created by akkamaddi, reliant on AleXndrTheGr8st. Maintained by Sinhika."
authors="akkamaddi, Sinhika"
description='''
Cobalt Ore and Cobalt Metal, with the alloys Blue Drift Steel, Blue Celadon,
and Green Celadon.
'''
[[dependencies.simplecobalt]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.simplecobalt]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"
    
[[dependencies.simplecobalt]]
    modId="simplecorelib"
    mandatory=true
    versionRange="[1.18.2-4.3.1.0,1.18.2-4.4.0.0)"
    ordering="NONE"
    side="BOTH"

[[dependencies.simplecobalt]]
    modId="simpleores"
    mandatory=false
    versionRange="[1.18.2-4.1.2.0,1.18.2-4.2.0.0)"
    ordering="BEFORE"
    side="BOTH"

[[dependencies.simplecobalt]]
    modId="fusion"
    mandatory=false
    versionRange="[1.18.2-4.1.1.0,1.18.2-4.2.0.0)"
    ordering="BEFORE"
    side="BOTH"

