# The overall format is standard TOML format, v0.5.0.
# The name of the mod loader type to load - for regular FML @Mod mods it should be javafml
modLoader="javafml" #mandatory

# A version range to match for said mod loader - for regular FML @Mod it will be the forge version
loaderVersion="${loader_version_range}" #mandatory
issueTrackerURL="https://github.com/Sinhika/simplecobalt/issues"
license="${mod_license}"
logoFile="logo.png"

[[mods]]
modId="${mod_id}"
version="${version}"
displayName="${mod_name}"
updateJSONURL="https://raw.githubusercontent.com/Sinhika/simplecobalt/1.20/update.json"
displayURL="https://www.curseforge.com/minecraft/mc-mods/simple-cobalt"
credits="Created by akkamaddi, reliant on AleXndrTheGr8st. Maintained by Sinhika."
authors="akkamaddi, Sinhika"
description='''
Cobalt Ore and Cobalt Metal, with the alloys Blue Drift Steel, Blue Celadon,
and Green Celadon.
'''
[[dependencies.${mod_id}]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
    
[[dependencies.${mod_id}]]
    modId="simplecorelib"
    mandatory=true
    versionRange="${simplecore_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="simpleores"
    mandatory=false
    versionRange="${simpleores_range}"
    ordering="BEFORE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="fusion"
    mandatory=false
    versionRange="${fusion_range}"
    ordering="BEFORE"
    side="BOTH"

